version: '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: appback
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
